### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by depau** [SargoDarya/webos-remote#1]
I'm running the program on Ubuntu 15.10, NodeJS v0.10.25.
When I start the server it prints `There you go, Remote listening on 127.0.0.1:3000`. However, when I open the web browser and try to access it, it says `Cannot GET /` and nothing else.

**Comment by SargoDarya** [comment]
Yepp, accidentally hard coded the IP, that might be the problem. Should be fixed with d9aad7bb396e859fabaf44813a169c5094bb018f

Can you try again?

**Comment by SargoDarya** [comment]
I'm closing this issue as I haven't heard back from you.

**Comment by depau** [comment]
Sorry, I forgot to answer. I currently can't test it as the TV is at my parents' house, and I won't be seeing them until August. I'll test it then. In the meantime, thank you.
